version: '3.7'

services:
   ilovedotnet:
    image: tictactoe-wasm
    build:
      context: .
      dockerfile: TicTacToe.UI/docker
    environment:
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"